### ISSUE TITLE
window.innerWidth is no longer being used

### ISSUE THREAD

**Issue by MasterKia** [jared-schwalbe/remove-ads-from-photopea#5]
Hi, the "restore width" code is broken due to this change:
`https://github.com/uBlockOrigin/uAssets/issues/19697#issuecomment-1713998773`

> Since you are re-setting window.innerWidth, I have switched to the property window.screen.width .

There needs to be a check to see if the window is already at its maximum size, as that's the case for premium users.

**Comment by krystian3w** [comment]
On my side, for those not logged in users it still works.

Of course, I am testing with `rpnt` (i.e. loss of page performance or too late replacement may occur).

They probably don't plan to create an account or pay for a subscription if logging in is not enough for them - so I won't help with detecting people who are logged in or paying the subscription.

**Comment by jared-schwalbe** [comment]
@MasterKia 

> Hi, the "restore width" code is broken due to this change:
https://github.com/uBlockOrigin/uAssets/issues/19697#issuecomment-1713998773

Following along, it seems that the creator changed to `window.screen.width`. However, I don't see the "restore width" functionality being broken on my end. I'm still able to resize the window and have the app width adjusted correctly. And it's just not worth it to me to debug something that I'm unable to reproduce.

> There needs to be a check to see if the window is already at its maximum size, as that's the case for premium users.

Why would a premium user be using this extension? My understanding is that a premium user shouldn't have the right panel that holds the ads...

**Comment by MasterKia** [comment]
@jared-schwalbe We use your code in uBlock Origin so that all users could have the maximum width and for premium users the UI gets broken, would you add a check to see if the UI is already at its maximum size (i.e. premium user)? Thank you.

**Comment by jared-schwalbe** [comment]
@MasterKia I have published a new release (still pending review in the chrome app store) that will check if the canvas is already at its maximum size. This should fix the problem that premium users had. Please review [app.js](https://github.com/jared-schwalbe/remove-ads-from-photopea/blob/main/app.js) and feel free to apply the same logic to uBlock or other ad blockers.

A couple of things to note:
- If the screen size (not the window size) is below 1500px then the ads width is actually 180px instead of 320px.
- Need to compare the size of the window to the size of the app container to see if the ads are present at all.
- If the window's width is smaller than it's height (so a vertical orientation) then the ads appear on the bottom and not the side. I didn't bother to account for this.
- If the Photopea developer sees this change then he can easily continue to update his code to circumvent this. Then it becomes a back and forth effort that I don't really want to engage in constantly.

**Comment by MasterKia** [comment]
I added this yesterday before your update:
```js
  const originalvisualViewport = window.visualViewport;

  Object.defineProperty(window, 'visualViewport', {
      value: new Proxy(originalvisualViewport, {
          get(target, property) {
              if (property === 'width') {
                  return document.documentElement.offsetWidth + 320;
              }
              return target[property];
          }
      }),
      configurable: true
  });
```

uBO already blocks the ads.
What kind of breakage should we expect?
I guess only this:
> If the screen size (not the window size) is below 1500px then the ads width is actually 180px instead of 320px.

**Comment by jared-schwalbe** [comment]
@MasterKia Okay good, updating the `window.visualViewport.width` was also how I got it to work again. Well I think you'll still have the problem of premium users having their viewport resized when it shouldn't be, which is what the Photopea developer was complaining about. And yes, you'll have issues when the screen size is below 1500px or the window is resized down to below 900px.

**Comment by MasterKia** [comment]
Thanks, I'll try to port the necessary parts from your script.

For the premium thing I just checked the localStorage to see if the user has logged in, probably not ideal, I will switch to your method.

**Comment by jared-schwalbe** [comment]
@MasterKia Yes that can be a problem because you can have an account (and be logged in) but not have premium. Unless there is a value you can check in localStorage to see if they have premium.
